### ISSUE TITLE
Some of the defined markup functions fail to render on latex.

### ISSUE THREAD

**Issue by divyaranjan1905** [otherjoel/try-pollen#14]
For example, when rendering a test file (using `pdflatex`), functions such as `blockcode` and `section` fail to render leaving the following trace:

```
pollen: rendering generated pagetree for directory /home/divya/src/racket/test-pollen/
pollen: rendering /example.poly.pm as html
pollen: rendered /example.html (693 ms)
pollen: rendering /example.poly.pm as ltx
pollen: rendered /example.ltx (982 ms)
pollen: rendering /example.poly.pm as pdf
string-append: contract violation
  expected: string?
  given: '(txt "\\begin{center}" "This text should be in the center." "\\end{center}")
  context...:
   body of 'g5817
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/render.rkt:411:0: render-markup-or-markdown-source
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/render.rkt:337:25: render
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/private/cache-utils.rkt:124:2: generate-dest-file
   /usr/share/racket/collects/file/cache.rkt:63:2: fetch-and-continue
   /usr/share/racket/collects/racket/contract/private/arrow-val-first.rkt:555:3
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/private/cache-utils.rkt:114:0: cache-ref!
   /usr/share/racket/collects/racket/private/more-scheme.rkt:377:2: hash-ref!
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/render.rkt:277:0: render-to-file-base
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/render.rkt:183:25: render-batch
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/private/command.rkt:149:9: render-one-dir
   /home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/private/external/logging.rkt:46:0: with-intercepted-logging
   body of (submod "/home/divya/.local/share/racket/8.12/pkgs/pollen/pollen/private/command.rkt" raco)
   /usr/share/racket/collects/raco/raco.rkt:41:0
   body of "/usr/share/racket/collects/raco/raco.rkt"
   body of "/usr/share/racket/collects/raco/main.rkt"
```

The minimal `pollen.rkt` that was used is the following:

```
#lang racket

(require pollen/decode
	       pollen/setup
	       txexpr)

(module setup racket/base
  (provide (all-defined-out))
  (define poly-targets '(html ltx pdf)))

(provide (all-defined-out))

(define (section title . text)
  (case (current-poly-target)
    [(ltx pdf) `(txt "\\section*{" ,title "}"
                 "\\label{sec:" ,title ,(symbol->string (gensym)) "}"
                 ,@text)]
    [else `(section (h2 ,title) ,@text)]))
    
(define (blockcode . text)
  (case (current-poly-target)
    [(ltx pdf) `(txt "\\begin{verbatim}" ,@text "\\end{verbatim}")]
    [else `(pre [[class "code"]] ,@text)]))
```

**Comment by divyaranjan1905** [comment]
I'd also note that this problem disappears if the functions are redefined without the use of `txt` which seems to be the culprit as the trace above shows.

So when I change the definition of `blockcode` to this:

```
(define (blockcode . text)
  (case (current-poly-target)
    [(ltx pdf) (apply string-append `("\\begin{verbatim}" ,@text "\\end{verbatim}"))]
    [else `(pre [[class "code"]] ,@text)]))
```

I get the desired block of code in the rendered pdf. The [Pollen documentation](https://docs.racket-lang.org/pollen/fourth-tutorial.html#(part._.Adding_support_for_.P.D.F_output)) too uses this.

I am going to be redefining all the required functions, maybe it's just a `pdflatex` issue? I don't have a configured `xelatex`, so when i tried to render one of the chapters in `flatland` it couldn't finish rendering.

I was initially thinking of changing the functions and sending a PR, but maybe a bit of discussion would be better first.

**Comment by otherjoel** [comment]
Yes, the functions as written require the use of [`txt-decode`](https://github.com/otherjoel/try-pollen/blob/1f15eb49ddd2d22c0d3d9954341adfab5d453b89/pollen.rkt#L62-L70) in concert with `decode` or `decode-elements`. [This repo does this in the `root` function](https://github.com/otherjoel/try-pollen/blob/1f15eb49ddd2d22c0d3d9954341adfab5d453b89/pollen.rkt#L39). I would expect to see this error if the code here is used without any use of `txt-decode` (such as in your minimal example).

Again, it’s been awhile but IIRC the reasoning was something like this. When a tag function emits strings of LaTeX, I wanted to be able to recognize those strings easily so I would be able to treat them differently than other strings when needed (such as during certain escaping operations). I did this by containing those strings within a `txt` X-expression. Then,`root` can strip out the `txt` tags at the very end of document evaluation, leaving only the inner strings.

Changing all the tag functions not to use the `txt` X-expressions as output is definitely one valid way to go. You may find that you never run into whatever problem I originally found that caused me to add this extra complication.

**Comment by divyaranjan1905** [comment]
Thank you, Joel! That makes sense. I've been just trying to dissect the `pollen.rkt` and see what's the most minimal one I can use for myself and making sure that I understand everything that I put in it :)
