### ISSUE TITLE
libuuid not available on Windows

### ISSUE THREAD

**Issue by j-maas** [otherjoel/try-pollen#7]
It appears that `libuuid` is not available on Windows, as the install `raco pkg install libuuid` fails, because `ffi-lib: couldn't open "libuuid-1.dll"` (the module does not exist).

Is there a way to fix this?

**Comment by j-maas** [comment]
It is possible to work around the issue by using the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by mtb-za** [comment]
Is there a way to do this without WSL? It is not available on the version of Windows that I have access to. I do have MinGW installed, but not sure how to point towards the libuuid.a file that it ships with.

**Comment by mtb-za** [comment]
Another possible workaround:

In `pollen.rkt`:
* Change: `require libuuid` to `require uuid`.
* Change any instances of `uuid-generate` to `uuid-string`.

I am not sure of the consequences of this change, but at least the ptree is loading now and I can see the website.
