### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by joelmccracken** [otherjoel/try-pollen#9]
I'm remaking my blog in pollen, and went looking for a RSS impl. Found yours. I dont see a licsense anywhere in this. Do you mind if I copy/modify the RSS feed code you have? 

This goes for other code, if you don't mind. Of course I won't touch any prose/design. 

Or not -- Just let me know. TY!

**Comment by otherjoel** [comment]
The code is all licensed under the MIT License! Details are in [`LICENSE.md`](https://github.com/otherjoel/try-pollen/blob/master/LICENSE.md). So do whatever you like with it. Glad to hear of another Pollen project.

**Comment by joelmccracken** [comment]
Derp, I see it now. Thanks!
